title: Musica para todos
description: Tienda de instrumentos musicales
author: Erwin Geovanny Solano chávez
avatar: /logo.png
email: geovannysolano15@hotmail.es

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
#
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
#
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username:
  card: summary
logo: logo.png
social:
  name: geovannysolano15
  links:
    - https://twitter.com/Synystergeo15
    - https://www.facebook.com/geovanny.solano15


lang: en
